import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 修改后的 layout.tsx 核心部分
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN">
      <body className="antialiased font-sans"> {/* 直接用 Tailwind 的系统字体类 */}
        {children}
      </body>
    </html>
  )
}
